import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { Inter } from 'next/font/google';

import { Toaster } from '@/components/ui/sonner';

const font = Inter({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} antialiased`}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
